### ISSUE TITLE
Require all exports to be named

### ISSUE THREAD

**Issue by dangaparker** [ArcadiaPower/eslint-config-arcadia#11]
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-default-export.md

**Comment by harkshark** [comment]
#tech-debt

**Comment by harkshark** [comment]
Need to poll the team for this one. Pretty much the opposite of how we write components in Jabiru:

https://github.com/ArcadiaPower/jabiru/compare/chore/linting/no-default-export

**Comment by harkshark** [comment]
Closing as team is not down for this.
